# config.yaml


## Congfiguration for fetch_data.py
# List of stock tickers to download
DOWNLOAD_STOCK_TICKER_LIST:
  - AAPL
  - SPY

# Download Intraday settings
INTRADAY_INTERVAL: "60min"   # One of: "1min", "5min", "15min", "30min", "60min"
OUTPUTSIZE: "full"           # "compact" (last 100 pts) or "full"

# Folder where CSVs will be saved
DATA_PATH: "./data"

# CAPM-related config (for later steps)
MARKET_PROXY: "SPY"          # Benchmark index (ETF ticker)
RISK_FREE_RATE:
  source: "FRED"             # Where to pull the risk-free rate
  series: "DTB3"             # 3-Month T-Bill series code at FRED



## Configuration for metrics.py
# List of stock tickers for calculations
STOCK_CALCULATION_LIST:
  - AAPL


# Calculation period
CALCULATION_START_DATE: "2020-01-01"
CALCULATION_END_DATE: "2023-12-31"